# Generated by Django 5.0.2 on 2024-02-20 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_register_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
