# Generated by Django 5.0.2 on 2024-02-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_rename_name_register_username'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='register',
        ),
    ]
