# Generated by Django 5.0.2 on 2024-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_register_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otpL', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'LOTP',
            },
        ),
        migrations.RemoveField(
            model_name='register',
            name='id',
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
