# Generated by Django 5.0.2 on 2024-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_lotp_remove_register_id_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
